name: Index.html deployment

on:
  push:
    branches:
    - master
jobs:
  build:
    name: Job1
    steps:
      - name: Checkout Index.html
        uses: actions/checkout@v4

      - name: Upload to build artifacts
        uses: actions/upload-artifact@v4.3.3

      - name: Deploy to  Netlify
        run: |
          netlify deploy --prod --dir=out --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }}

