name: Index.html deployment

on:
  push:
    branches:
    - master
jobs:
  build:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Index.html
        uses: actions/checkout@v4

      - name: Upload to build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
        #SHA value of build hash
        # name: ${{ github.sha }}
          name: upload index.html
          path: index.html

      - name: Deploy to  Netlify
        run: |
          netlify deploy --prod --dir=out --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }}

